name: muslim_way
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.2+3

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  share_plus: ^4.0.3
  scrollable_positioned_list: ^0.2.3
  geolocator: ^7.6.2
  flutter_bloc: ^8.1.1
  dio: ^4.0.4
  get: ^4.6.5 #for navigation
  get_storage: ^2.0.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: quran
      fonts:
        - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/me_quran.ttf
